sudo: required
dist: trusty
language: python
cache: pip3
python:
  - "3.5"
# command to install dependencies
install:
  - cd tests
  - sudo apt-get -y install python3-pip
  - pip3 install bs4
  - pip install coveralls
script: 
  - python3 test_getemails.py
  - python3 test_getweblinks.py
  - python3 test_savetofile.py
  - coverage run --source=torBot,python3 test_getemails.py
after_success:
  coveralls
notifications:
    slack: dedsec-inside:24NHg47gypeVR3DWnEncRq7c
